# Generated by Django 3.1 on 2020-08-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200828_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Product',
        ),
    ]
